"""empty message

Revision ID: 66ecf3704e5e
Revises: 9771c9a8811c
Create Date: 2020-04-12 15:48:43.910210

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '66ecf3704e5e'
down_revision = '9771c9a8811c'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('profiles', sa.Column('location', sa.String(length=255), nullable=True))
    op.drop_column('profiles', 'loctation')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('profiles', sa.Column('loctation', sa.VARCHAR(length=255), autoincrement=False, nullable=True))
    op.drop_column('profiles', 'location')
    # ### end Alembic commands ###
